### ISSUE TITLE
Gulp Install

### ISSUE THREAD

**Issue by izorgor** [evanw/packer#7]
I`m trying to install the plugin via NPM and I`m getting this error every single time

```
$ npm install --save-dev gulp-packer

> contextify@0.1.15 install C:\test\node_modules\contextify
> node-gyp rebuild


C:\test\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Pro                                           gram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp                                           \bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python2.7", you can set the                                            PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod                                           e_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node                                           -gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej                                           s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\test\node_modules\contextify
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
test@1.0.0 C:\test
`-- gulp@3.9.1

npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                           node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp-packer"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\test\npm-debug.log
```
Thanks

**Comment by Julienh** [comment]
Same problem here : 

```
C:\Users\test\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\np
m\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )                     
gyp ERR! configure error                                                                                                
gyp ERR! stack Error: Can't find Python executable "C:\Python32\python.EXE", you can set the PYTHON env variable.       
gyp ERR! stack     at Object.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.
js:482:19)                                                                                                              
gyp ERR! stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.j
s:508:16)                                                                                                               
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29             
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)                                                               
gyp ERR! System Windows_NT 10.0.15063                                                                                   
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"                                                                                       
gyp ERR! cwd C:\Users\test\node_modules\contextify                                                                     
gyp ERR! node -v v6.10.1                                                                                                
gyp ERR! node-gyp -v v3.6.0                                                                                             
gyp ERR! not ok                                                                                                         
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\test\package.json'                                   
npm WARN test No description                                                                                           
npm WARN test No repository field.                                                                                     
npm WARN test No README data                                                                                           
npm WARN test No license field.                                                                                        
npm ERR! code ELIFECYCLE                                                                                                
npm ERR! errno 1                                                                                                        
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`                                                                  
npm ERR! Exit status 1                                                                                                  
npm ERR!                                                                                                                
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.                                             
npm ERR! Make sure you have the latest version of node.js and npm installed.                                            
npm ERR! If you do, this is most likely a problem with the contextify package,                                          
npm ERR! not with npm itself.                                                                                           
npm ERR! Tell the author that this fails on your system:                                                                
npm ERR!     node-gyp rebuild                                                                                           
npm ERR! You can get information on how to open an issue for this project with:                                         
npm ERR!     npm bugs contextify                                                                                        
npm ERR! Or if that isn't available, you can get their info via:                                                        
npm ERR!     npm owner ls contextify                                                                                    
npm ERR! There is likely additional logging output above.                                                               
                                                                                                                        
npm ERR! A complete log of this run can be found in:                                                                    
npm ERR!     C:\Users\test\AppData\Roaming\npm-cache\_logs\2017-05-25T09_54_09_968Z-debug.log                          
                                                                                                                        
```
